apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: selfsigned-mq-cluster-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "257"
spec:
  ca:
    secretName: mq-self-signed-ca-cert
